# Generated by Django 2.1.4 on 2018-12-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('img_link', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
