# Generated by Django 2.1.4 on 2018-12-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_color',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='product_color',
            name='id',
        ),
        migrations.AddField(
            model_name='product_color',
            name='combi_name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
