# Generated by Django 2.1.4 on 2018-12-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20181216_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_color',
            name='combi_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
