# Generated by Django 2.1.4 on 2018-12-15 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_auto_20181216_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_color',
            name='device_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mall.Product'),
        ),
    ]
