# Generated by Django 2.1.4 on 2018-12-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_product_color_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_color',
            name='device_name',
            field=models.CharField(max_length=30),
        ),
    ]
