# Generated by Django 2.1.4 on 2018-12-16 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_auto_20181217_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_color',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_color',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
