# Generated by Django 2.1.4 on 2018-12-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0009_auto_20181217_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='updated_datetime',
        ),
        migrations.RenameField(
            model_name='product_color',
            old_name='created',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='product_color',
            old_name='updated',
            new_name='updated_datetime',
        ),
    ]
