# Generated by Django 2.1.4 on 2018-12-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_auto_20181217_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_datetime',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product_color',
            old_name='created_datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product_color',
            old_name='updated_datetime',
            new_name='updated_at',
        ),
    ]
